/**
 * WP-04 — `ROUTE_SURFACE_MAP`: one future surface per canonical route, 79/79.
 *
 * Generated from `docs/ui-overhaul/ROUTE_SURFACE_MATRIX.csv` by
 * `scripts/generate-route-surface-map.mjs`, then committed and owned by hand.
 * It is not regenerated at build time on purpose: the matrix is an audit
 * artifact, and a build step that silently rewrote runtime routing would make an
 * edit to a docs CSV a production change.
 *
 * Two independent gates keep the copy honest:
 *   - `scripts/check-ui-route-coverage.mjs` — exact set equality against
 *     `APP_ROUTE_REGISTRY` and the matrix. Fails on a missing route, a ghost
 *     route, or a duplicate key.
 *   - `route-surface-map.test.ts` — field-level equality against the matrix for
 *     hub, canonical path, surface type, placement, and permanent-nav status.
 *
 * Unlock rules are deliberately absent. `routeUnlock()` reads them from the
 * engine registry so there is exactly one copy of when a destination opens.
 */

import { appRoute, type AppRouteDefinition } from '@mfd/engine/config';
import { normalizePath } from './href';
import type { HubId, RouteSurfaceMeta } from './route-surface-types';

export const ROUTE_SURFACE_MAP: Record<string, RouteSurfaceMeta> = {
  '/': {
    legacyPath: '/',
    hub: 'today',
    canonicalPath: '/today',
    surfaceType: 'phase-aware-hub',
    placement: 'Today overview',
    permanentNav: true,
    frequency: 'every-session',
    urgency: 'critical',
  },
  '/week-advance': {
    legacyPath: '/week-advance',
    hub: 'today',
    canonicalPath: '/today?panel=readiness',
    surfaceType: 'drawer',
    placement: 'sticky gated Advance control',
    permanentNav: false,
    frequency: 'weekly',
    urgency: 'critical',
  },
  '/inbox': {
    legacyPath: '/inbox',
    hub: 'today',
    canonicalPath: '/today/inbox',
    surfaceType: 'hub-section',
    placement: 'Today > Inbox',
    permanentNav: false,
    frequency: 'frequent',
    urgency: 'high',
  },
  '/watch-list': {
    legacyPath: '/watch-list',
    hub: 'today',
    canonicalPath: '/today/watchlist',
    surfaceType: 'hub-section',
    placement: 'Today > Watchlist',
    permanentNav: false,
    frequency: 'frequent',
    urgency: 'medium',
  },
  '/roster': {
    legacyPath: '/roster',
    hub: 'team',
    canonicalPath: '/team/roster',
    surfaceType: 'collection',
    placement: 'Team default',
    permanentNav: true,
    frequency: 'very-frequent',
    urgency: 'high',
  },
  '/depth-chart': {
    legacyPath: '/depth-chart',
    hub: 'team',
    canonicalPath: '/team/depth',
    surfaceType: 'hub-section',
    placement: 'Team > Depth',
    permanentNav: false,
    frequency: 'very-frequent',
    urgency: 'critical-when-blocked',
  },
  '/locker-room': {
    legacyPath: '/locker-room',
    hub: 'team',
    canonicalPath: '/team/culture',
    surfaceType: 'hub-section',
    placement: 'Team > Culture',
    permanentNav: false,
    frequency: 'weekly',
    urgency: 'medium',
  },
  '/coaching': {
    legacyPath: '/coaching',
    hub: 'team',
    canonicalPath: '/team/staff',
    surfaceType: 'phase-aware-hub',
    placement: 'Team > Staff',
    permanentNav: false,
    frequency: 'periodic',
    urgency: 'medium',
  },
  '/coaching/tree': {
    legacyPath: '/coaching/tree',
    hub: 'team',
    canonicalPath: '/team/staff/tree',
    surfaceType: 'hub-section',
    placement: 'Team > Staff > Tree',
    permanentNav: false,
    frequency: 'occasional',
    urgency: 'low',
  },
  '/coaching/relationships': {
    legacyPath: '/coaching/relationships',
    hub: 'team',
    canonicalPath: '/team/staff/relationships',
    surfaceType: 'hub-section',
    placement: 'Team > Staff > Relationships',
    permanentNav: false,
    frequency: 'periodic',
    urgency: 'medium',
  },
  '/handshakes': {
    legacyPath: '/handshakes',
    hub: 'team',
    canonicalPath: '/team/commitments',
    surfaceType: 'hub-section',
    placement: 'Team > Culture > Commitments',
    permanentNav: false,
    frequency: 'weekly',
    urgency: 'high-when-due',
  },
  '/training-camp': {
    legacyPath: '/training-camp',
    hub: 'team',
    canonicalPath: '/team/camp',
    surfaceType: 'contextual-workflow',
    placement: 'phase takeover + Team tab',
    permanentNav: false,
    frequency: 'phase-dominant',
    urgency: 'critical',
  },
  '/mentors': {
    legacyPath: '/mentors',
    hub: 'team',
    canonicalPath: '/team/development/mentors',
    surfaceType: 'hub-section',
    placement: 'Team > Development > Mentors',
    permanentNav: false,
    frequency: 'occasional',
    urgency: 'medium',
  },
  '/player-development': {
    legacyPath: '/player-development',
    hub: 'team',
    canonicalPath: '/team/development',
    surfaceType: 'phase-aware-hub',
    placement: 'Team > Development',
    permanentNav: false,
    frequency: 'weekly',
    urgency: 'high',
  },
  '/compare': {
    legacyPath: '/compare',
    hub: 'team',
    canonicalPath: '/team/compare',
    surfaceType: 'comparison-workbench',
    placement: 'contextual entity action',
    permanentNav: false,
    frequency: 'contextual',
    urgency: 'medium',
  },
  '/rivalries': {
    legacyPath: '/rivalries',
    hub: 'team',
    canonicalPath: '/team/culture/rivalries',
    surfaceType: 'hub-section',
    placement: 'Team > Culture > Rivalries',
    permanentNav: false,
    frequency: 'occasional',
    urgency: 'low',
  },
  '/contracts': {
    legacyPath: '/contracts',
    hub: 'office',
    canonicalPath: '/office/finance/contracts',
    surfaceType: 'hub-section',
    placement: 'Office > Finance > Contracts',
    permanentNav: false,
    frequency: 'frequent',
    urgency: 'high',
  },
  '/cap-lab': {
    legacyPath: '/cap-lab',
    hub: 'office',
    canonicalPath: '/office/finance/cap-lab',
    surfaceType: 'transaction-workbench',
    placement: 'Office > Finance > Cap Lab',
    permanentNav: false,
    frequency: 'periodic',
    urgency: 'medium',
  },
  '/front-office': {
    legacyPath: '/front-office',
    hub: 'office',
    canonicalPath: '/office/operations',
    surfaceType: 'phase-aware-hub',
    placement: 'Office > Operations',
    permanentNav: true,
    frequency: 'weekly',
    urgency: 'medium',
  },
  '/endorsements': {
    legacyPath: '/endorsements',
    hub: 'office',
    canonicalPath: '/office/operations/endorsements',
    surfaceType: 'hub-section',
    placement: 'Office > Operations > Endorsements',
    permanentNav: false,
    frequency: 'occasional',
    urgency: 'low',
  },
  '/trades': {
    legacyPath: '/trades',
    hub: 'office',
    canonicalPath: '/office/personnel/trades',
    surfaceType: 'transaction-workbench',
    placement: 'Office > Personnel > Trades',
    permanentNav: false,
    frequency: 'periodic',
    urgency: 'high-when-active',
  },
  '/trade-block': {
    legacyPath: '/trade-block',
    hub: 'office',
    canonicalPath: '/office/personnel/trade-market',
    surfaceType: 'hub-section',
    placement: 'Office > Personnel > Market',
    permanentNav: false,
    frequency: 'weekly',
    urgency: 'medium',
  },
  '/trade-deadline': {
    legacyPath: '/trade-deadline',
    hub: 'office',
    canonicalPath: '/office/personnel/deadline',
    surfaceType: 'contextual-workflow',
    placement: 'deadline phase takeover + Today task',
    permanentNav: false,
    frequency: 'phase-dominant',
    urgency: 'critical',
  },
  '/team-needs': {
    legacyPath: '/team-needs',
    hub: 'office',
    canonicalPath: '/office/personnel/needs',
    surfaceType: 'hub-section',
    placement: 'Office > Personnel > Needs',
    permanentNav: false,
    frequency: 'weekly',
    urgency: 'high',
  },
  '/scouting': {
    legacyPath: '/scouting',
    hub: 'office',
    canonicalPath: '/office/personnel/scouting',
    surfaceType: 'phase-aware-hub',
    placement: 'Office > Personnel > Scouting',
    permanentNav: false,
    frequency: 'frequent-in-phase',
    urgency: 'high',
  },
  '/draft': {
    legacyPath: '/draft',
    hub: 'office',
    canonicalPath: '/office/personnel/draft',
    surfaceType: 'decision-workflow',
    placement: 'draft phase takeover + Office tab',
    permanentNav: false,
    frequency: 'phase-dominant',
    urgency: 'critical',
  },
  '/draft-recap': {
    legacyPath: '/draft-recap',
    hub: 'office',
    canonicalPath: '/office/personnel/draft/recap',
    surfaceType: 'event-presentation',
    placement: 'draft completion + archive',
    permanentNav: false,
    frequency: 'once-per-season',
    urgency: 'medium',
  },
  '/expansion-draft': {
    legacyPath: '/expansion-draft',
    hub: 'office',
    canonicalPath: '/office/personnel/expansion-draft',
    surfaceType: 'decision-workflow',
    placement: 'event-driven Office workflow',
    permanentNav: false,
    frequency: 'rare',
    urgency: 'critical-when-active',
  },
  '/free-agency': {
    legacyPath: '/free-agency',
    hub: 'office',
    canonicalPath: '/office/personnel/free-agency',
    surfaceType: 'transaction-workbench',
    placement: 'free-agency takeover + Office tab',
    permanentNav: false,
    frequency: 'phase-dominant',
    urgency: 'critical',
  },
  '/fa-targets': {
    legacyPath: '/fa-targets',
    hub: 'office',
    canonicalPath: '/office/personnel/free-agency/targets',
    surfaceType: 'hub-section',
    placement: 'Free Agency > Targets',
    permanentNav: false,
    frequency: 'frequent-in-phase',
    urgency: 'high',
  },
  '/waivers': {
    legacyPath: '/waivers',
    hub: 'office',
    canonicalPath: '/office/personnel/waivers',
    surfaceType: 'hub-section',
    placement: 'Office > Personnel > Waivers',
    permanentNav: false,
    frequency: 'weekly',
    urgency: 'medium',
  },
  '/practice-squad': {
    legacyPath: '/practice-squad',
    hub: 'team',
    canonicalPath: '/team/roster/practice-squad',
    surfaceType: 'hub-section',
    placement: 'Team > Roster > Practice Squad',
    permanentNav: false,
    frequency: 'weekly',
    urgency: 'medium',
  },
  '/owner': {
    legacyPath: '/owner',
    hub: 'office',
    canonicalPath: '/office/ownership',
    surfaceType: 'hub-section',
    placement: 'Office > Ownership',
    permanentNav: false,
    frequency: 'periodic',
    urgency: 'high-when-triggered',
  },
  '/relocate': {
    legacyPath: '/relocate',
    hub: 'office',
    canonicalPath: '/office/ownership/relocation',
    surfaceType: 'decision-workflow',
    placement: 'Office > Ownership > Relocation',
    permanentNav: false,
    frequency: 'rare',
    urgency: 'high-when-active',
  },
  '/game-plan': {
    legacyPath: '/game-plan',
    hub: 'game',
    canonicalPath: '/game/plan',
    surfaceType: 'hub-section',
    placement: 'Game > Plan + Today task',
    permanentNav: false,
    frequency: 'weekly',
    urgency: 'critical',
  },
  '/game-day': {
    legacyPath: '/game-day',
    hub: 'game',
    canonicalPath: '/game/current',
    surfaceType: 'event-presentation',
    placement: 'Game Center overview',
    permanentNav: true,
    frequency: 'weekly',
    urgency: 'critical',
  },
  '/broadcast': {
    legacyPath: '/broadcast',
    hub: 'game',
    canonicalPath: '/game/current/broadcast',
    surfaceType: 'hub-section',
    placement: 'Game Center > Broadcast',
    permanentNav: false,
    frequency: 'weekly',
    urgency: 'medium',
  },
  '/presentation': {
    legacyPath: '/presentation',
    hub: 'game',
    canonicalPath: '/game/current/presentation',
    surfaceType: 'hub-section',
    placement: 'Game Center > Presentation',
    permanentNav: false,
    frequency: 'weekly',
    urgency: 'medium',
  },
  '/play-by-play': {
    legacyPath: '/play-by-play',
    hub: 'game',
    canonicalPath: '/game/current/play-by-play',
    surfaceType: 'hub-section',
    placement: 'Game Center > Play-by-Play',
    permanentNav: false,
    frequency: 'weekly',
    urgency: 'medium',
  },
  '/game-flow': {
    legacyPath: '/game-flow',
    hub: 'game',
    canonicalPath: '/game/current/flow',
    surfaceType: 'hub-section',
    placement: 'Game Center > Flow',
    permanentNav: false,
    frequency: 'weekly',
    urgency: 'medium',
  },
  '/film-room': {
    legacyPath: '/film-room',
    hub: 'game',
    canonicalPath: '/game/current/film',
    surfaceType: 'hub-section',
    placement: 'Game Center > Film',
    permanentNav: false,
    frequency: 'weekly',
    urgency: 'high',
  },
  '/schedule': {
    legacyPath: '/schedule',
    hub: 'game',
    canonicalPath: '/game/schedule',
    surfaceType: 'hub-section',
    placement: 'Game > Schedule',
    permanentNav: false,
    frequency: 'frequent',
    urgency: 'medium',
  },
  '/super-bowl': {
    legacyPath: '/super-bowl',
    hub: 'game',
    canonicalPath: '/game/super-bowl',
    surfaceType: 'event-presentation',
    placement: 'championship takeover + archive',
    permanentNav: false,
    frequency: 'rare',
    urgency: 'critical-when-active',
  },
  '/standings': {
    legacyPath: '/standings',
    hub: 'league',
    canonicalPath: '/league/standings',
    surfaceType: 'hub-section',
    placement: 'League default',
    permanentNav: true,
    frequency: 'weekly',
    urgency: 'high',
  },
  '/power-rankings': {
    legacyPath: '/power-rankings',
    hub: 'league',
    canonicalPath: '/league/rankings',
    surfaceType: 'hub-section',
    placement: 'League > Rankings',
    permanentNav: false,
    frequency: 'weekly',
    urgency: 'medium',
  },
  '/league-pulse': {
    legacyPath: '/league-pulse',
    hub: 'league',
    canonicalPath: '/league/pulse',
    surfaceType: 'timeline',
    placement: 'League > Pulse',
    permanentNav: false,
    frequency: 'weekly',
    urgency: 'medium',
  },
  '/league/weather': {
    legacyPath: '/league/weather',
    hub: 'league',
    canonicalPath: '/league/weather',
    surfaceType: 'hub-section',
    placement: 'League > Context > Weather',
    permanentNav: false,
    frequency: 'weekly',
    urgency: 'low',
  },
  '/newsroom': {
    legacyPath: '/newsroom',
    hub: 'league',
    canonicalPath: '/league/news',
    surfaceType: 'timeline',
    placement: 'League > News',
    permanentNav: false,
    frequency: 'weekly',
    urgency: 'medium',
  },
  '/news': {
    legacyPath: '/news',
    hub: 'league',
    canonicalPath: '/league/news/all',
    surfaceType: 'hub-section',
    placement: 'League > News > All',
    permanentNav: false,
    frequency: 'frequent',
    urgency: 'medium',
  },
  '/social': {
    legacyPath: '/social',
    hub: 'league',
    canonicalPath: '/league/news/mfsn',
    surfaceType: 'hub-section',
    placement: 'League > News > MFSN',
    permanentNav: false,
    frequency: 'frequent',
    urgency: 'low',
  },
  '/commissioner': {
    legacyPath: '/commissioner',
    hub: 'league',
    canonicalPath: '/league/governance/commissioner',
    surfaceType: 'hub-section',
    placement: 'League > Governance',
    permanentNav: false,
    frequency: 'occasional',
    urgency: 'medium',
  },
  '/cba': {
    legacyPath: '/cba',
    hub: 'league',
    canonicalPath: '/league/governance/cba',
    surfaceType: 'decision-workflow',
    placement: 'event-driven governance workflow',
    permanentNav: false,
    frequency: 'rare',
    urgency: 'critical-when-active',
  },
  '/league-rules': {
    legacyPath: '/league-rules',
    hub: 'league',
    canonicalPath: '/league/governance/rules',
    surfaceType: 'hub-section',
    placement: 'League > Governance > Rules',
    permanentNav: false,
    frequency: 'occasional',
    urgency: 'low',
  },
  '/analytics': {
    legacyPath: '/analytics',
    hub: 'league',
    canonicalPath: '/league/analytics',
    surfaceType: 'dashboard',
    placement: 'League > Analytics',
    permanentNav: false,
    frequency: 'periodic',
    urgency: 'medium',
  },
  '/records': {
    legacyPath: '/records',
    hub: 'league',
    canonicalPath: '/league/history/records',
    surfaceType: 'archive-detail',
    placement: 'League > History > Records',
    permanentNav: false,
    frequency: 'occasional',
    urgency: 'low',
  },
  '/stat-central': {
    legacyPath: '/stat-central',
    hub: 'league',
    canonicalPath: '/league/stats',
    surfaceType: 'collection',
    placement: 'League > Stats',
    permanentNav: false,
    frequency: 'frequent',
    urgency: 'medium',
  },
  '/franchise': {
    legacyPath: '/franchise',
    hub: 'dynasty',
    canonicalPath: '/dynasty/overview',
    surfaceType: 'phase-aware-hub',
    placement: 'Dynasty overview',
    permanentNav: false,
    frequency: 'periodic',
    urgency: 'medium',
  },
  '/legends': {
    legacyPath: '/legends',
    hub: 'dynasty',
    canonicalPath: '/dynasty/legends',
    surfaceType: 'archive-detail',
    placement: 'Dynasty > Legends',
    permanentNav: false,
    frequency: 'occasional',
    urgency: 'low',
  },
  '/franchise/career': {
    legacyPath: '/franchise/career',
    hub: 'dynasty',
    canonicalPath: '/dynasty/career',
    surfaceType: 'dashboard',
    placement: 'Dynasty > Career',
    permanentNav: false,
    frequency: 'periodic',
    urgency: 'medium',
  },
  '/franchise/book': {
    legacyPath: '/franchise/book',
    hub: 'dynasty',
    canonicalPath: '/dynasty/book',
    surfaceType: 'archive-detail',
    placement: 'Dynasty > Archive > Book',
    permanentNav: false,
    frequency: 'occasional',
    urgency: 'low',
  },
  '/franchise/chronicle': {
    legacyPath: '/franchise/chronicle',
    hub: 'dynasty',
    canonicalPath: '/dynasty/chronicle',
    surfaceType: 'timeline',
    placement: 'Dynasty > Archive > Chronicle',
    permanentNav: false,
    frequency: 'occasional',
    urgency: 'low',
  },
  '/franchise/scrapbook': {
    legacyPath: '/franchise/scrapbook',
    hub: 'dynasty',
    canonicalPath: '/dynasty/scrapbook',
    surfaceType: 'archive-detail',
    placement: 'Dynasty > Archive > Scrapbook',
    permanentNav: false,
    frequency: 'occasional',
    urgency: 'low',
  },
  '/franchise/hall': {
    legacyPath: '/franchise/hall',
    hub: 'dynasty',
    canonicalPath: '/dynasty/hall-of-fame',
    surfaceType: 'archive-detail',
    placement: 'Dynasty > Honors > Hall of Fame',
    permanentNav: false,
    frequency: 'occasional',
    urgency: 'low',
  },
  '/franchise/trophy-room': {
    legacyPath: '/franchise/trophy-room',
    hub: 'dynasty',
    canonicalPath: '/dynasty/trophies',
    surfaceType: 'archive-detail',
    placement: 'Dynasty > Honors > Trophies',
    permanentNav: false,
    frequency: 'occasional',
    urgency: 'medium',
  },
  '/franchise/eras': {
    legacyPath: '/franchise/eras',
    hub: 'dynasty',
    canonicalPath: '/dynasty/eras',
    surfaceType: 'timeline',
    placement: 'Dynasty > History > Eras',
    permanentNav: false,
    frequency: 'occasional',
    urgency: 'low',
  },
  '/franchise/mvps': {
    legacyPath: '/franchise/mvps',
    hub: 'dynasty',
    canonicalPath: '/dynasty/honors/mvps',
    surfaceType: 'archive-detail',
    placement: 'Dynasty > Honors > MVPs',
    permanentNav: false,
    frequency: 'occasional',
    urgency: 'low',
  },
  '/franchise/playoff-lore': {
    legacyPath: '/franchise/playoff-lore',
    hub: 'dynasty',
    canonicalPath: '/dynasty/history/playoffs',
    surfaceType: 'archive-detail',
    placement: 'Dynasty > History > Playoffs',
    permanentNav: false,
    frequency: 'occasional',
    urgency: 'low',
  },
  '/franchise/achievements': {
    legacyPath: '/franchise/achievements',
    hub: 'dynasty',
    canonicalPath: '/dynasty/achievements',
    surfaceType: 'dashboard',
    placement: 'Dynasty > Achievements',
    permanentNav: false,
    frequency: 'periodic',
    urgency: 'medium',
  },
  '/legacy': {
    legacyPath: '/legacy',
    hub: 'dynasty',
    canonicalPath: '/dynasty/legacy',
    surfaceType: 'hub-section',
    placement: 'Dynasty > Legacy',
    permanentNav: false,
    frequency: 'periodic',
    urgency: 'medium',
  },
  '/legacy/named-games': {
    legacyPath: '/legacy/named-games',
    hub: 'dynasty',
    canonicalPath: '/dynasty/history/named-games',
    surfaceType: 'archive-detail',
    placement: 'Dynasty > History > Named Games',
    permanentNav: false,
    frequency: 'occasional',
    urgency: 'low',
  },
  '/legacy/bloodlines': {
    legacyPath: '/legacy/bloodlines',
    hub: 'dynasty',
    canonicalPath: '/dynasty/history/bloodlines',
    surfaceType: 'archive-detail',
    placement: 'Dynasty > History > Bloodlines',
    permanentNav: false,
    frequency: 'occasional',
    urgency: 'low',
  },
  '/awards': {
    legacyPath: '/awards',
    hub: 'dynasty',
    canonicalPath: '/dynasty/honors/awards',
    surfaceType: 'archive-detail',
    placement: 'Dynasty > Honors > Awards',
    permanentNav: false,
    frequency: 'periodic',
    urgency: 'medium',
  },
  '/season/recap': {
    legacyPath: '/season/recap',
    hub: 'dynasty',
    canonicalPath: '/dynasty/seasons/current/recap',
    surfaceType: 'event-presentation',
    placement: 'season-completion event + archive',
    permanentNav: false,
    frequency: 'once-per-season',
    urgency: 'high',
  },
  '/scenarios': {
    legacyPath: '/scenarios',
    hub: 'dynasty',
    canonicalPath: '/scenarios',
    surfaceType: 'collection',
    placement: 'Title screen + Dynasty > Challenges',
    permanentNav: false,
    frequency: 'occasional',
    urgency: 'low',
  },
  '/about': {
    legacyPath: '/about',
    hub: 'system',
    canonicalPath: '/system/about',
    surfaceType: 'system-utility',
    placement: 'System sheet > About',
    permanentNav: false,
    frequency: 'rare',
    urgency: 'low',
  },
  '/credits': {
    legacyPath: '/credits',
    hub: 'system',
    canonicalPath: '/system/credits',
    surfaceType: 'system-utility',
    placement: 'System sheet > Credits',
    permanentNav: false,
    frequency: 'rare',
    urgency: 'low',
  },
  '/faq': {
    legacyPath: '/faq',
    hub: 'system',
    canonicalPath: '/help',
    surfaceType: 'system-utility',
    placement: 'Help search + System sheet',
    permanentNav: false,
    frequency: 'occasional',
    urgency: 'medium',
  },
  '/dynasty': {
    legacyPath: '/dynasty',
    hub: 'system',
    canonicalPath: '/system/saves',
    surfaceType: 'trust-critical-utility',
    placement: 'System sheet > Saves',
    permanentNav: false,
    frequency: 'periodic',
    urgency: 'critical',
  },
  '/settings': {
    legacyPath: '/settings',
    hub: 'system',
    canonicalPath: '/system/settings',
    surfaceType: 'trust-critical-utility',
    placement: 'System sheet > Settings',
    permanentNav: false,
    frequency: 'periodic',
    urgency: 'medium',
  },
};

export const ROUTE_SURFACE_ENTRIES: readonly RouteSurfaceMeta[] = Object.values(ROUTE_SURFACE_MAP);

/** Normalises first, so `/roster/` and `roster` find the same surface a link would. */
export function routeSurface(legacyPath: string): RouteSurfaceMeta | undefined {
  return ROUTE_SURFACE_MAP[normalizePath(legacyPath)];
}

export function hubForLegacyPath(legacyPath: string): HubId | undefined {
  return routeSurface(legacyPath)?.hub;
}

export function routesInHub(hub: HubId): readonly RouteSurfaceMeta[] {
  return ROUTE_SURFACE_ENTRIES.filter((entry) => entry.hub === hub);
}

/**
 * Unlock metadata, read straight from the canonical registry rather than copied.
 * Returns undefined for a path the registry does not know, which is the same
 * signal `resolveCompatibleRoute` uses to report an unknown destination.
 */
export function routeUnlock(
  legacyPath: string,
): Pick<AppRouteDefinition, 'unlockWeek' | 'unlockPhase'> | undefined {
  const definition = appRoute(normalizePath(legacyPath));
  if (!definition) return undefined;
  return { unlockWeek: definition.unlockWeek, unlockPhase: definition.unlockPhase };
}
