export const REQUIRED_CHIP_FEATURES = [
  'monday-briefing',
  'week-advance',
  'inbox',
  'roster',
  'depth-chart',
  'injuries',
  'game-plan',
  'coaching',
  'contracts',
  'cap-lab',
  'trades',
  'team-needs',
  'scouting',
  'draft',
  'free-agency',
  'waiver-wire',
  'practice-squad',
  'film-room',
  'schedule',
  'standings',
  'power-rankings',
  'league-pulse',
  'analytics',
  'record-book',
  'dynasty-save-load',
  'settings',
] as const;

export type ChipFeatureId = (typeof REQUIRED_CHIP_FEATURES)[number];

export type ChipFeatureIntroductionMoment =
  | 'first_ten_minutes'
  | 'weekly_loop'
  | 'post_result'
  | 'decision_pressure'
  | 'cap_pressure'
  | 'roster_pressure'
  | 'deadline_window'
  | 'offseason'
  | 'draft_window'
  | 'deep_dive';

export type ChipFeatureTestStatus = 'route_beat' | 'state_machine' | 'manual_check' | 'scaffolded' | 'missing';

export interface ChipFeatureVisibilityEntry {
  id: ChipFeatureId;
  feature: string;
  entryPoint: string;
  whatItDoes: string;
  whyItMatters: string;
  bestMoment: ChipFeatureIntroductionMoment;
  firstTimePlayerAction: string;
  advancedPlayerNote: string;
  testStatus: ChipFeatureTestStatus;
}

export const FIRST_TEN_MINUTE_FEATURES: readonly ChipFeatureId[] = [
  'monday-briefing',
  'roster',
  'depth-chart',
  'game-plan',
  'week-advance',
] as const;

export const CHIP_FEATURE_VISIBILITY_MATRIX: readonly ChipFeatureVisibilityEntry[] = [
  {
    id: 'monday-briefing',
    feature: 'Monday Briefing',
    entryPoint: '/',
    whatItDoes: 'Separates Must Do, Recommended, and Optional work from injuries, owner patience, next opponent, and deadlines.',
    whyItMatters: 'Monday Briefing names what must be fixed or accepted before Advance Week locks injuries, morale, standings, and deadlines.',
    bestMoment: 'first_ten_minutes',
    firstTimePlayerAction: 'Open Action Center for current notes; then any legal roster, cap, Game Plan, trade, market, staff, or medical move stays available before Advance Week.',
    advancedPlayerNote: 'Order injuries, offers, promises, cap, and matchup work without blocking legal roster, cap, plan, trade, or staff moves.',
    testStatus: 'state_machine',
  },
  {
    id: 'inbox',
    feature: 'Inbox',
    entryPoint: '/inbox',
    whatItDoes: 'Holds offers, promises, votes, owner requests, and deadlines that need choose-or-defer decisions.',
    whyItMatters: 'Offers, promises, votes, lineup, cap, and morale choices expire or lock at Advance Week.',
    bestMoment: 'weekly_loop',
    firstTimePlayerAction: 'Open Inbox for offers, promises, votes, and owner requests before Advance Week.',
    advancedPlayerNote: 'Answer deadline choices before Advance Week; leave no-deadline messages for later when they do not change lineup, cap, or morale.',
    testStatus: 'route_beat',
  },
  {
    id: 'roster',
    feature: 'Roster',
    entryPoint: '/roster',
    whatItDoes: 'Names health, roles, age, contract cost, and first-backup jobs before lineup or cap moves.',
    whyItMatters: 'Set starters and first backups before Game Plan; uncovered backup jobs, injuries, and contract mistakes waste the next matchup.',
    bestMoment: 'first_ten_minutes',
    firstTimePlayerAction: 'Open roster injuries and first-backup jobs before setting the plan.',
    advancedPlayerNote: 'Name aging starters, expiring contracts, and crowded roles before the first extension, trade, or draft pick.',
    testStatus: 'route_beat',
  },
  {
    id: 'depth-chart',
    feature: 'Depth Chart',
    entryPoint: '/depth-chart',
    whatItDoes: 'Saves starters, package roles, and first backups for game day.',
    whyItMatters: 'Set first backups before Advance Week; the saved order decides who replaces an injured starter.',
    bestMoment: 'first_ten_minutes',
    firstTimePlayerAction: 'Set starters and first backups at vulnerable positions before Advance Week.',
    advancedPlayerNote: 'Set nickel, goal-line, and injury backup jobs before blitz-heavy, pass-heavy, or injury-heavy weeks; missing package jobs put a player without that assignment on the field.',
    testStatus: 'route_beat',
  },
  {
    id: 'injuries',
    feature: 'Injuries',
    entryPoint: '/roster',
    whatItDoes: 'Names limited or out players and the first-backup or Game Plan change they force.',
    whyItMatters: 'Injured starters change saved depth and Game Plan calls; ignoring them puts an unassigned first backup on the field.',
    bestMoment: 'roster_pressure',
    firstTimePlayerAction: 'Open Roster first when a starter is limited or out.',
    advancedPlayerNote: 'Identify injury clusters before saving depth so one position group is not exposed.',
    testStatus: 'manual_check',
  },
  {
    id: 'game-plan',
    feature: 'Game Plan',
    entryPoint: '/game-plan',
    whatItDoes: 'Saves offensive focus, protection, coverage, and run calls used by the next game.',
    whyItMatters: 'Combine opponent scouting, injuries, and player limits before Advance Week; calls beyond starter ratings expose missed protection or coverage.',
    bestMoment: 'first_ten_minutes',
    firstTimePlayerAction: 'Pick offensive focus, protection, and coverage calls that injured players have enough health and ratings to handle.',
    advancedPlayerNote: 'Match opponent strengths to injuries before accepting tradeoffs; calls beyond healthy-player ratings create missed protection, coverage, or run-defense assignments.',
    testStatus: 'route_beat',
  },
  {
    id: 'week-advance',
    feature: 'Advance Week',
    entryPoint: '/week-advance',
    whatItDoes: 'Runs the league forward after required lineup choices and Game Plan calls are set.',
    whyItMatters: 'Advance Week locks games, injuries, morale, standings, and answered or ignored deadlines.',
    bestMoment: 'first_ten_minutes',
    firstTimePlayerAction: 'Open Advance Week and cover injuries, missing starters, offers, promises, or phase rules before continuing.',
    advancedPlayerNote: 'Leave optional moves undone when lineups, deadlines, and matchup calls are acceptable; Advance Week still locks the choices you leave.',
    testStatus: 'route_beat',
  },
  {
    id: 'coaching',
    feature: 'Coaching',
    entryPoint: '/coaching',
    whatItDoes: 'Names coach-owned QB, line, coverage, defender, scheme, and development-snap jobs.',
    whyItMatters: 'Staff choices change prep quality, player growth, and the assignments current starters must learn before kickoff.',
    bestMoment: 'deep_dive',
    firstTimePlayerAction: 'Open Coaching after Monday Briefing, starters, and Game Plan are set; match each coach to the roles your starters will run before Advance Week.',
    advancedPlayerNote: 'Open Staff and Depth Chart before signing or drafting; a coach who cannot teach the role slows prep and development.',
    testStatus: 'route_beat',
  },
  {
    id: 'contracts',
    feature: 'Contracts',
    entryPoint: '/contracts',
    whatItDoes: 'Names current deals, cut cost, extension cost, dead money, and cap obligations before contract moves lock.',
    whyItMatters: 'Contract moves without role and dead-money preview spend cap space needed for injury replacements, extensions, or deadline trades.',
    bestMoment: 'cap_pressure',
    firstTimePlayerAction: 'Open Contracts when cap space is tight, a core player is expiring, or a cut/restructure creates dead money.',
    advancedPlayerNote: 'Preview dead money and next-year cap before cutting or restructuring; one-week relief blocks injury replacements or extensions.',
    testStatus: 'manual_check',
  },
  {
    id: 'cap-lab',
    feature: 'Cap Lab',
    entryPoint: '/cap-lab',
    whatItDoes: 'Previews restructures, cuts, and extensions before you apply them.',
    whyItMatters: 'Preview cap moves here before applying them; stacked restructures, void years, and backloads create dead money or block extensions.',
    bestMoment: 'cap_pressure',
    firstTimePlayerAction: 'Preview one cap move at a time; name cap space, dead money, extension cap space, and injury-replacement money before applying.',
    advancedPlayerNote: 'Preview cap space created today against dead money and extension limits next offseason.',
    testStatus: 'route_beat',
  },
  {
    id: 'trades',
    feature: 'Trades',
    entryPoint: '/trades',
    whatItDoes: 'Accepts, counters, blocks, and proposes trades that move players, picks, cap space, and morale.',
    whyItMatters: 'Trades solve one starter or backup job while adding cap cost, player complaints, or lost picks.',
    bestMoment: 'deadline_window',
    firstTimePlayerAction: 'Open the trade impact panel before accepting or proposing.',
    advancedPlayerNote: 'Buy when the new starter changes the next two games enough to pay the cap, pick, and morale cost; otherwise hold or sell before the deadline.',
    testStatus: 'route_beat',
  },
  {
    id: 'team-needs',
    feature: 'Team Needs',
    entryPoint: '/team-needs',
    whatItDoes: 'Ranks position shortages and spots with too few playable backups.',
    whyItMatters: 'Open Team Needs after the same matchup miss repeats; ignoring the same position shortage lets it decide another week.',
    bestMoment: 'post_result',
    firstTimePlayerAction: 'Open Team Needs after a loss exposes the same matchup miss twice, before another week repeats it.',
    advancedPlayerNote: 'Pair position shortages with cap and draft picks before a major move; fixing one starter job leaves the next backup, cap, or pick shortage exposed.',
    testStatus: 'route_beat',
  },
  {
    id: 'scouting',
    feature: 'Scouting',
    entryPoint: '/scouting',
    whatItDoes: 'Shows prospect role, medical, trait, and roster-job warnings before draft week.',
    whyItMatters: 'Scout future starter and backup jobs before draft week; missing role answers, medical limits, or coachability reports force a reach or veteran overpay.',
    bestMoment: 'draft_window',
    firstTimePlayerAction: 'Open Scouting when Team Needs or calendar timing points there; waiting too long removes cheaper draft choices.',
    advancedPlayerNote: 'Match traits to staff and scheme before trusting a prospect; a role mismatch turns a talented player into a wasted pick.',
    testStatus: 'route_beat',
  },
  {
    id: 'draft',
    feature: 'Draft',
    entryPoint: '/draft',
    whatItDoes: 'Turns scout reports and Team Needs into rookie picks.',
    whyItMatters: 'Draft picks fill roster jobs cheaply, but a miss costs the pick and leaves veteran cap costs unsolved.',
    bestMoment: 'draft_window',
    firstTimePlayerAction: 'Open Team Needs, scout reports, and cap space; name the player role before making the pick.',
    advancedPlayerNote: 'Pick an immediate starter when rookie contract timing and depth both fill a named lineup job.',
    testStatus: 'manual_check',
  },
  {
    id: 'free-agency',
    feature: 'Free Agency',
    entryPoint: '/free-agency',
    whatItDoes: 'Signs veterans for named starter, backup, or injury-replacement jobs.',
    whyItMatters: 'Free Agency fills starter or backup jobs fast, but long veteran deals block injury replacements, extensions, or next-offseason cap space.',
    bestMoment: 'offseason',
    firstTimePlayerAction: 'Open Free Agency after Team Needs names a role and cap-space limit; sign one exact role before spending across several positions.',
    advancedPlayerNote: 'Avoid paying veterans for every open role; long deals block cheaper draft or injury fixes.',
    testStatus: 'route_beat',
  },
  {
    id: 'waiver-wire',
    feature: 'Waiver Wire',
    entryPoint: '/waivers',
    whatItDoes: 'Claims short-term backups for one-week injury, return, or special-teams jobs.',
    whyItMatters: 'Claim emergency backups before injuries force a low-role emergency starter or missed depth-chart saves.',
    bestMoment: 'roster_pressure',
    firstTimePlayerAction: 'Open Waivers when a one-week injury or backup emergency would force a low-role emergency starter before Advance Week.',
    advancedPlayerNote: 'Claim emergency depth before changing long-term starters; claims without a weekly job cost roster spots.',
    testStatus: 'route_beat',
  },
  {
    id: 'practice-squad',
    feature: 'Practice Squad',
    entryPoint: '/practice-squad',
    whatItDoes: 'Stashes or elevates low-cost backups for injuries, special teams, and assigned future roles.',
    whyItMatters: 'Practice Squad protects low-cost depth before injuries or roster churn force emergency signings.',
    bestMoment: 'roster_pressure',
    firstTimePlayerAction: 'Open Practice Squad when injuries leave a backup job uncovered.',
    advancedPlayerNote: 'Stash or elevate depth with assigned scheme jobs before waivers or injuries take away cheap backups.',
    testStatus: 'route_beat',
  },
  {
    id: 'film-room',
    feature: 'Film Room',
    entryPoint: '/film-room',
    whatItDoes: 'Shows protection, coverage, run-defense assignment, and play-call misses after results.',
    whyItMatters: 'Open Film Room to decide whether the fix is roster, depth chart, or Game Plan before the mistake repeats.',
    bestMoment: 'post_result',
    firstTimePlayerAction: 'Open Film Room after a result exposes protection, coverage, run-defense, or lineup miss; repeated misses cost next week too.',
    advancedPlayerNote: 'If the same protection, coverage, or run-defense miss repeats, fix Game Plan or Depth Chart before changing personnel.',
    testStatus: 'route_beat',
  },
  {
    id: 'schedule',
    feature: 'Schedule',
    entryPoint: '/schedule',
    whatItDoes: 'Names upcoming opponents, byes, short weeks, and weather that change rest and calls.',
    whyItMatters: 'Wind, rain, short weeks, and byes decide whether to rest starters, add depth, shorten throws, or call more runs.',
    bestMoment: 'weekly_loop',
    firstTimePlayerAction: 'Open Schedule after Monday Briefing; short weeks, byes, and weather decide rest, depth, quick throws, or more runs before Advance Week.',
    advancedPlayerNote: 'Plan roster moves and starter rest for multi-week stretches before spending cap space or picks.',
    testStatus: 'manual_check',
  },
  {
    id: 'standings',
    feature: 'Standings',
    entryPoint: '/standings',
    whatItDoes: 'Names playoff position, division deficit, and league position before buy, sell, or hold choices.',
    whyItMatters: 'Open Standings before the deadline; a 3-4 buyer needs one starter who changes the wild-card race, while buying at 2-6 wastes picks and cap.',
    bestMoment: 'post_result',
    firstTimePlayerAction: 'Open Standings before buying or selling when the playoff race or division deficit changes pick and cap cost.',
    advancedPlayerNote: 'Choose buy, sell, or hold from division deficit, wild-card line, and schedule; rushed deadline moves cost picks, cap space, or playoff ground.',
    testStatus: 'route_beat',
  },
  {
    id: 'power-rankings',
    feature: 'Power Rankings',
    entryPoint: '/power-rankings',
    whatItDoes: 'Separates public rank from record, point margin, injuries, and fan reaction before image-driven moves.',
    whyItMatters: 'Open Power Rankings after results to explain fan reaction and owner patience; standings still decide playoff position and owner demands.',
    bestMoment: 'deep_dive',
    firstTimePlayerAction: 'Open Power Rankings after injuries are handled, roster moves are saved, Game Plan is set, and Advance Week runs.',
    advancedPlayerNote: 'Name public ranking, standings, injuries, and point margin before trades or benchings; moves for rank alone cost picks, cap, or starters.',
    testStatus: 'route_beat',
  },
  {
    id: 'league-pulse',
    feature: 'League Pulse / News',
    entryPoint: '/league-pulse',
    whatItDoes: 'Names rival injuries, rivalries, standings deficits, trade timing, and free-agency timing before buy, sell, or wait choices.',
    whyItMatters: 'Open League Pulse after your own Roster, cap space, and Game Plan are set; rival injuries and trade timing decide whether you buy, sell, or wait.',
    bestMoment: 'weekly_loop',
    firstTimePlayerAction: 'Open it after your own Roster, cap space, and Game Plan decisions are set.',
    advancedPlayerNote: 'Open league news before trade or free-agency moves; missed alerts leave a bid late or a matchup exposed.',
    testStatus: 'route_beat',
  },
  {
    id: 'analytics',
    feature: 'Analytics',
    entryPoint: '/analytics',
    whatItDoes: 'Shows repeated team and player trends before roster, lineup, or Game Plan choices lock in.',
    whyItMatters: 'Open Analytics after repeated protection, coverage, rushing, turnover, or efficiency misses; one odd box score cuts, trades, or benches needed role players.',
    bestMoment: 'deep_dive',
    firstTimePlayerAction: 'Open Analytics after the same protection, coverage, rushing, turnover, or efficiency miss repeats; find the trend before cutting, trading, or benching a player.',
    advancedPlayerNote: 'Require repeated trends before cutting or trading; one odd box score removes a starter who still fills a role.',
    testStatus: 'manual_check',
  },
  {
    id: 'record-book',
    feature: 'Record Book / Legacy Systems',
    entryPoint: '/records',
    whatItDoes: 'Prices roles, extensions, and trades with records, milestones, and franchise history without changing the current week.',
    whyItMatters: 'Open Records before role, extension, or trade choices; production sets price, but injuries, cap, depth, and calls still need their own screens.',
    bestMoment: 'deep_dive',
    firstTimePlayerAction: 'Open Records after roster, cap, depth, and Game Plan choices are saved; stats help price roles, deals, and trades.',
    advancedPlayerNote: 'Open Records before legacy goals, extensions, or trades; current production should support the role or price change.',
    testStatus: 'route_beat',
  },
  {
    id: 'dynasty-save-load',
    feature: 'Dynasty Save/Load',
    entryPoint: '/dynasty',
    whatItDoes: 'Exports backup files, imports cartridges, and saves local slots before trades, imports, or offseason sequences replace progress.',
    whyItMatters: 'Exporting gives you a rollback before an import replaces the current dynasty, a trade spends picks or cap space, or offseason moves lock.',
    bestMoment: 'decision_pressure',
    firstTimePlayerAction: 'Export or copy a portable dynasty before an import, major trade, or offseason sequence.',
    advancedPlayerNote: 'Validate files in a separate backup slot before replacing the current dynasty; an invalid file or old save should not take over the only copy.',
    testStatus: 'route_beat',
  },
  {
    id: 'settings',
    feature: 'Settings',
    entryPoint: '/settings',
    whatItDoes: 'Saves difficulty, autosave, audio, motion, pacing, accessibility, and Chip quieting before future results.',
    whyItMatters: 'Settings decide difficulty, autosave, pace, and Chip guidance before the next Advance Week creates results.',
    bestMoment: 'decision_pressure',
    firstTimePlayerAction: 'Open Settings before Advance Week when difficulty, autosave, motion, pacing, or Chip quieting needs to change.',
    advancedPlayerNote: 'Change settings before Advance Week; saved results are not rewritten after the week exists.',
    testStatus: 'route_beat',
  },
] as const;

export function getFeatureVisibilityEntry(id: string): ChipFeatureVisibilityEntry | null {
  return CHIP_FEATURE_VISIBILITY_MATRIX.find((entry) => entry.id === id) ?? null;
}
