export const REQUIRED_CHIP_FEATURES = [
  'monday-briefing',
  'week-advance',
  'inbox',
  'roster',
  'depth-chart',
  'injuries',
  'game-plan',
  'coaching',
  'contracts',
  'cap-lab',
  'trades',
  'team-needs',
  'scouting',
  'draft',
  'free-agency',
  'waiver-wire',
  'practice-squad',
  'film-room',
  'schedule',
  'standings',
  'power-rankings',
  'league-pulse',
  'analytics',
  'record-book',
  'settings-save-load',
] as const;

export type ChipFeatureId = (typeof REQUIRED_CHIP_FEATURES)[number];

export type ChipFeatureIntroductionMoment =
  | 'first_ten_minutes'
  | 'weekly_loop'
  | 'post_result'
  | 'decision_pressure'
  | 'cap_pressure'
  | 'roster_pressure'
  | 'deadline_window'
  | 'offseason'
  | 'draft_window'
  | 'deep_dive';

export type ChipFeatureTestStatus = 'route_beat' | 'state_machine' | 'manual_check' | 'scaffolded' | 'missing';

export interface ChipFeatureVisibilityEntry {
  id: ChipFeatureId;
  feature: string;
  entryPoint: string;
  whatItDoes: string;
  whyItMatters: string;
  bestMoment: ChipFeatureIntroductionMoment;
  firstTimePlayerAction: string;
  advancedPlayerNote: string;
  testStatus: ChipFeatureTestStatus;
}

export const FIRST_TEN_MINUTE_FEATURES: readonly ChipFeatureId[] = [
  'monday-briefing',
  'roster',
  'depth-chart',
  'game-plan',
  'week-advance',
] as const;

export const CHIP_FEATURE_VISIBILITY_MATRIX: readonly ChipFeatureVisibilityEntry[] = [
  {
    id: 'monday-briefing',
    feature: 'Monday Briefing',
    entryPoint: '/',
    whatItDoes: 'Summarizes the current week, latest result, risks, and most urgent context.',
    whyItMatters: 'It gives the player a football reason to choose the next screen.',
    bestMoment: 'first_ten_minutes',
    firstTimePlayerAction: 'Read the briefing before touching the roster or advance button.',
    advancedPlayerNote: 'Use it as the weekly triage board, not a full report.',
    testStatus: 'state_machine',
  },
  {
    id: 'inbox',
    feature: 'Inbox',
    entryPoint: '/inbox',
    whatItDoes: 'Collects urgent team decisions and league prompts.',
    whyItMatters: 'Unresolved items can travel into the sim and change outcomes.',
    bestMoment: 'weekly_loop',
    firstTimePlayerAction: 'Clear urgent decisions before advancing the week.',
    advancedPlayerNote: 'Use inbox timing to decide what can safely wait.',
    testStatus: 'route_beat',
  },
  {
    id: 'roster',
    feature: 'Roster',
    entryPoint: '/roster',
    whatItDoes: 'Shows the player group, roles, health, age, and roster quality.',
    whyItMatters: 'A strategy only works if the bodies can execute it.',
    bestMoment: 'first_ten_minutes',
    firstTimePlayerAction: 'Find injured starters and thin positions before setting the plan.',
    advancedPlayerNote: 'Use age and role clusters to anticipate future replacement needs.',
    testStatus: 'route_beat',
  },
  {
    id: 'depth-chart',
    feature: 'Depth Chart',
    entryPoint: '/depth-chart',
    whatItDoes: 'Turns roster talent into the actual Sunday lineup.',
    whyItMatters: 'One bad backup slot can turn a good plan into a bad game.',
    bestMoment: 'first_ten_minutes',
    firstTimePlayerAction: 'Check starters and first backups at vulnerable positions.',
    advancedPlayerNote: 'Tune depth before aggressive game plans or injury-heavy weeks.',
    testStatus: 'route_beat',
  },
  {
    id: 'injuries',
    feature: 'Injuries',
    entryPoint: '/roster',
    whatItDoes: 'Shows who is limited, out, or forcing a lineup adjustment.',
    whyItMatters: 'Injuries change both the depth chart and the game-plan risk.',
    bestMoment: 'roster_pressure',
    firstTimePlayerAction: 'Treat injured starters as the first roster question.',
    advancedPlayerNote: 'Plan around clusters, not just the highest-rated injured player.',
    testStatus: 'manual_check',
  },
  {
    id: 'game-plan',
    feature: 'Game Plan',
    entryPoint: '/game-plan',
    whatItDoes: 'Sets the weekly offensive and defensive approach.',
    whyItMatters: 'It converts scouting and roster reality into a bet against the opponent.',
    bestMoment: 'first_ten_minutes',
    firstTimePlayerAction: 'Pick a plan your roster can survive, not just one that attacks the opponent.',
    advancedPlayerNote: 'Use opponent shape and injury context to accept or avoid tradeoffs.',
    testStatus: 'route_beat',
  },
  {
    id: 'week-advance',
    feature: 'Week Advance',
    entryPoint: '/week-advance',
    whatItDoes: 'Runs the league forward after readiness checks and game-plan gates.',
    whyItMatters: 'It is where decisions become consequences.',
    bestMoment: 'first_ten_minutes',
    firstTimePlayerAction: 'Read the checklist and fix any red item before simming.',
    advancedPlayerNote: 'Veterans can intentionally advance with risk when the window justifies it.',
    testStatus: 'route_beat',
  },
  {
    id: 'coaching',
    feature: 'Coaching',
    entryPoint: '/staff',
    whatItDoes: 'Frames staff identity, scheme support, and development pressure.',
    whyItMatters: 'Staff choices explain why players improve, stall, or fit a system.',
    bestMoment: 'deep_dive',
    firstTimePlayerAction: 'Skim staff strengths after the weekly loop is understood.',
    advancedPlayerNote: 'Use staff fit to guide roster construction over multiple seasons.',
    testStatus: 'route_beat',
  },
  {
    id: 'contracts',
    feature: 'Contracts',
    entryPoint: '/contracts',
    whatItDoes: 'Shows player deals, cuts, extensions, and cap obligations.',
    whyItMatters: 'The football window is constrained by the money window.',
    bestMoment: 'cap_pressure',
    firstTimePlayerAction: 'Open contracts when Chip flags cap pressure or expiring core players.',
    advancedPlayerNote: 'Read future commitments before solving one week with a costly move.',
    testStatus: 'manual_check',
  },
  {
    id: 'cap-lab',
    feature: 'Cap Lab',
    entryPoint: '/cap-lab',
    whatItDoes: 'Lets the player sandbox restructures, cuts, and extensions.',
    whyItMatters: 'It makes the future bill visible before the player commits.',
    bestMoment: 'cap_pressure',
    firstTimePlayerAction: 'Preview a cap move and read immediate, season, future, and risk impact.',
    advancedPlayerNote: 'Use it to compare room today against dead money tomorrow.',
    testStatus: 'route_beat',
  },
  {
    id: 'trades',
    feature: 'Trades',
    entryPoint: '/trades',
    whatItDoes: 'Shows incoming offers and lets the player build proposals.',
    whyItMatters: 'Trades solve roster problems but create cap, chemistry, and future-asset bills.',
    bestMoment: 'deadline_window',
    firstTimePlayerAction: 'Read the trade impact panel before accepting or proposing.',
    advancedPlayerNote: 'Use contender/rebuild timing to judge whether the risk belongs now.',
    testStatus: 'route_beat',
  },
  {
    id: 'team-needs',
    feature: 'Team Needs',
    entryPoint: '/team-needs',
    whatItDoes: 'Ranks roster holes and pressure points.',
    whyItMatters: 'It connects weekly pain to offseason priorities.',
    bestMoment: 'post_result',
    firstTimePlayerAction: 'Check needs after a loss exposes the same weakness twice.',
    advancedPlayerNote: 'Pair needs with cap and draft capital before making a major move.',
    testStatus: 'manual_check',
  },
  {
    id: 'scouting',
    feature: 'Scouting',
    entryPoint: '/scouting',
    whatItDoes: 'Surfaces prospect information before the draft window.',
    whyItMatters: 'It connects today’s weaknesses to tomorrow’s replacements.',
    bestMoment: 'draft_window',
    firstTimePlayerAction: 'Wait for Chip to introduce scouting when team needs or calendar timing point there.',
    advancedPlayerNote: 'Track traits that match staff and scheme instead of chasing board noise.',
    testStatus: 'route_beat',
  },
  {
    id: 'draft',
    feature: 'Draft',
    entryPoint: '/draft',
    whatItDoes: 'Turns scouting and team needs into rookie acquisition.',
    whyItMatters: 'It is the cheapest path to changing a franchise arc.',
    bestMoment: 'draft_window',
    firstTimePlayerAction: 'Use needs, scouting, and cap context before making the pick.',
    advancedPlayerNote: 'Balance immediate starter value against contract-window planning.',
    testStatus: 'manual_check',
  },
  {
    id: 'free-agency',
    feature: 'Free Agency',
    entryPoint: '/free-agency',
    whatItDoes: 'Lets the team buy veteran solutions on the open market.',
    whyItMatters: 'It fills holes quickly but can distort the cap window.',
    bestMoment: 'offseason',
    firstTimePlayerAction: 'Use free agency after team needs and cap pressure are clear.',
    advancedPlayerNote: 'Avoid turning every gap into a long-term veteran bill.',
    testStatus: 'manual_check',
  },
  {
    id: 'waiver-wire',
    feature: 'Waiver Wire',
    entryPoint: '/waivers',
    whatItDoes: 'Offers short-term roster repairs and depth options.',
    whyItMatters: 'It keeps a season alive when injuries hit the wrong position.',
    bestMoment: 'roster_pressure',
    firstTimePlayerAction: 'Use waivers when Chip flags an injury or depth emergency.',
    advancedPlayerNote: 'Treat waivers as leverage for depth, not a franchise reset.',
    testStatus: 'manual_check',
  },
  {
    id: 'practice-squad',
    feature: 'Practice Squad',
    entryPoint: '/practice-squad',
    whatItDoes: 'Stores developmental depth outside the active lineup.',
    whyItMatters: 'It gives the player cheap answers to injuries and future churn.',
    bestMoment: 'roster_pressure',
    firstTimePlayerAction: 'Check it when depth chart injuries create a backup problem.',
    advancedPlayerNote: 'Use it to protect scheme-fit developmental players.',
    testStatus: 'manual_check',
  },
  {
    id: 'film-room',
    feature: 'Film Room',
    entryPoint: '/film-room',
    whatItDoes: 'Explains performance trends and matchup lessons after results.',
    whyItMatters: 'It separates bad process from football variance.',
    bestMoment: 'post_result',
    firstTimePlayerAction: 'Open film after Chip says the result exposed a plan or roster issue.',
    advancedPlayerNote: 'Use repeated tells to adjust scheme before changing personnel.',
    testStatus: 'route_beat',
  },
  {
    id: 'schedule',
    feature: 'Schedule',
    entryPoint: '/schedule',
    whatItDoes: 'Shows upcoming opponents and calendar pressure.',
    whyItMatters: 'The next three weeks change how aggressive a move should be.',
    bestMoment: 'weekly_loop',
    firstTimePlayerAction: 'Check the next opponent after reading the briefing.',
    advancedPlayerNote: 'Plan roster and rest risk around stretches, not single games.',
    testStatus: 'manual_check',
  },
  {
    id: 'standings',
    feature: 'Standings',
    entryPoint: '/standings',
    whatItDoes: 'Shows playoff race, division context, and league position.',
    whyItMatters: 'A 3-4 team in a weak division makes different decisions than a buried one.',
    bestMoment: 'post_result',
    firstTimePlayerAction: 'Check standings when Chip mentions playoff or division pressure.',
    advancedPlayerNote: 'Use standings to decide buy, sell, or hold near the deadline.',
    testStatus: 'route_beat',
  },
  {
    id: 'power-rankings',
    feature: 'Power Rankings',
    entryPoint: '/power-rankings',
    whatItDoes: 'Frames perception and team strength relative to the league.',
    whyItMatters: 'It makes momentum and reputation visible without replacing standings.',
    bestMoment: 'deep_dive',
    firstTimePlayerAction: 'Use it after the weekly loop makes sense.',
    advancedPlayerNote: 'Treat rankings as league narrative, not a perfect team grade.',
    testStatus: 'route_beat',
  },
  {
    id: 'league-pulse',
    feature: 'League Pulse / News',
    entryPoint: '/league-pulse',
    whatItDoes: 'Shows league stories, news, and outside context.',
    whyItMatters: 'It makes the franchise feel embedded in a living league.',
    bestMoment: 'weekly_loop',
    firstTimePlayerAction: 'Read it after clearing your own urgent team work.',
    advancedPlayerNote: 'Use league context to spot market and rivalry timing.',
    testStatus: 'route_beat',
  },
  {
    id: 'analytics',
    feature: 'Analytics',
    entryPoint: '/analytics',
    whatItDoes: 'Turns team and player trends into deeper evidence.',
    whyItMatters: 'It helps the player validate whether a weakness is real.',
    bestMoment: 'deep_dive',
    firstTimePlayerAction: 'Open analytics after Chip flags a repeated problem.',
    advancedPlayerNote: 'Use trends to challenge surface ratings and recent bias.',
    testStatus: 'manual_check',
  },
  {
    id: 'record-book',
    feature: 'Record Book / Legacy Systems',
    entryPoint: '/records',
    whatItDoes: 'Preserves history, milestones, and franchise memory.',
    whyItMatters: 'It gives multi-season play emotional weight.',
    bestMoment: 'deep_dive',
    firstTimePlayerAction: 'Visit records after the first season starts creating history.',
    advancedPlayerNote: 'Use legacy context to make long saves feel authored.',
    testStatus: 'route_beat',
  },
  {
    id: 'settings-save-load',
    feature: 'Settings / Save Load',
    entryPoint: '/settings',
    whatItDoes: 'Controls preferences, save/load, and guidance behavior.',
    whyItMatters: 'It keeps players in control of Chip, persistence, and accessibility.',
    bestMoment: 'decision_pressure',
    firstTimePlayerAction: 'Use settings to replay, reset, reduce, or re-enable Chip guidance.',
    advancedPlayerNote: 'Tune guidance without disabling the underlying game depth.',
    testStatus: 'route_beat',
  },
] as const;

export function getFeatureVisibilityEntry(id: string): ChipFeatureVisibilityEntry | null {
  return CHIP_FEATURE_VISIBILITY_MATRIX.find((entry) => entry.id === id) ?? null;
}
