/**
 * Deterministic UI fixtures for the UI/UX reinvention.
 *
 * Every builder returns a fresh `GameState` from a fixed seed, then sets
 * lifecycle fields declaratively. Builders deliberately do **not** call store
 * mutations or `advanceWeek` to reach a phase: driving the simulation forward
 * would consume RNG and make the fixture depend on execution order, which is
 * exactly the failure mode WP-00 exists to prevent.
 *
 * These are test/evidence helpers only. They must never be imported by
 * production code or become seed logic.
 */

import { getActiveRule, type GameState } from '@mfd/engine';
import { createSeedGameState } from '../../../app/store/seed';

/** One seed for every fixture keeps cross-fixture comparisons meaningful. */
export const UI_FIXTURE_SEED = 424242;

export type UiFixtureId =
  | 'newGame'
  | 'regularSeasonEarly'
  | 'regularSeasonWeek14'
  | 'tradeDeadline'
  | 'tradeDeadlineExpired'
  | 'playoffs'
  | 'offseason'
  | 'freeAgency'
  | 'draft'
  | 'trainingCamp';

function baseState(): GameState {
  return createSeedGameState(UI_FIXTURE_SEED, 0, 'pro');
}

/** Read the live rule rather than hardcoding 9, so the fixture tracks league rules. */
export function resolveTradeDeadlineWeek(game: GameState): number {
  if (!game.leagueRules) return 9;
  const week = Number(getActiveRule(game.leagueRules, 'trade_deadline_week', game.year));
  return Number.isFinite(week) ? week : 9;
}

function atPhase(phase: GameState['phase'], week: number): GameState {
  const game = baseState();
  game.phase = phase;
  game.week = week;
  return game;
}

export const uiOverhaulFixtures: Record<UiFixtureId, () => GameState> = {
  /** Cold open: nothing decided yet. Backs J-01 and the LAY-05 setup budget. */
  newGame: () => atPhase('preseason', 1),

  /** Early regular season, before most weekly obligations accumulate. */
  regularSeasonEarly: () => atPhase('regular_season', 2),

  /** The reference week for the M2 weekly-loop script and LAY-04 Today budget. */
  regularSeasonWeek14: () => atPhase('regular_season', 14),

  /** Deadline still open — Office > Personnel should foreground the trade desk. */
  tradeDeadline: () => {
    const game = baseState();
    game.phase = 'regular_season';
    game.week = resolveTradeDeadlineWeek(game);
    return game;
  },

  /** Deadline passed — the same surfaces must explain the closed window. */
  tradeDeadlineExpired: () => {
    const game = baseState();
    game.phase = 'regular_season';
    game.week = resolveTradeDeadlineWeek(game) + 1;
    return game;
  },

  playoffs: () => atPhase('playoffs', 19),
  offseason: () => atPhase('offseason', 1),
  freeAgency: () => atPhase('free_agency', 1),
  draft: () => atPhase('draft', 1),
  trainingCamp: () => atPhase('training_camp', 1),
};

export const UI_FIXTURE_IDS = Object.keys(uiOverhaulFixtures) as UiFixtureId[];

export function buildUiFixture(id: UiFixtureId): GameState {
  return uiOverhaulFixtures[id]();
}

/**
 * Multi-season legacy states are intentionally absent.
 *
 * A truthful long-dynasty fixture requires actually simulating seasons — the
 * records, awards, archives and franchise history it must exercise cannot be
 * hand-authored without the fixture lying about engine output. The packet that
 * first needs it (WP-20 Dynasty, or the M6 long-dynasty script) should generate
 * it by running the existing playtest harness and caching the result, rather
 * than fabricating history here.
 */
export const LONG_DYNASTY_FIXTURE_NOTE =
  'Long-dynasty fixtures must be generated by simulation, not hand-authored. See WP-20 / manual script M6.';
